name: dylan-merqato
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.12.9
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.1
      - cramjam==2.9.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fastparquet==2024.11.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.2.4
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - platformdirs==4.3.7
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - wandb==0.19.9
